# Generated by Django 2.0 on 2018-01-08 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityscore_by_mentor',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
