# Generated by Django 2.0 on 2018-01-11 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voiceapp', '0002_auto_20180108_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Teams', to='Voiceapp.Team'),
        ),
    ]
