# Generated by Django 2.0 on 2018-01-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voiceapp', '0003_auto_20180111_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Candidates', to='Voiceapp.Candidate'),
        ),
        migrations.AlterField(
            model_name='activityscore_by_mentor',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to='Voiceapp.Activity'),
        ),
    ]
